
elaticjob:
  zookeeper:
    server-lists: localhost:2181
    namespace: my-job

#simpleJob:
#  cron: 0/5 * * * * ?
#  shardingTotalCount: 3
#  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
#
#dataflowJob:
#  cron: 0/5 * * * * ?
#  shardingTotalCount: 3
#  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou